# https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_Form
digit                     = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
lower-case-letter         = "a" | ... ;
upper-case-letter         = "A" | ... ;
letter                    = upper-case-letter | lower-case-letter ;
camel-case                = upper-case-letter, { letter | digit } ;
snake-case                = lower-case-letter, { letter | digit | "_" } ;
type-name                 = camel-case ;
contract-name             = camel-case ;
variable-name             = snake-case ;
function-name             = snake-case ;
type-var-name             = snake-case ;

type-var-name-list        = type-var-name { ",", type-var-name } ;

type                      =

where-limit               = type-var-name, "of", type ;
where-limit-list          = where-limit { ",", where-limit } ;
function-decl             = "type", function-name, "(", function-param-list, ")", [ "where", where-limit-list ], ";" ;

contract-decl             = "contract", contract-name, [ "with", type-var-name-list ], "{", contract-decl-content, "}" ;
contract-decl-content     = function-decl, "{", function-decl, "}" ;

api-decl                  = "api", "{", api-decl-content, "}" ;
api-decl-content          = type-decl
                          | contract-decl
                          | function-decl
                          | api-decl-content ;

main                      = api-decl
                          | api-impl
                          | type-decl
                          | type-definition
                          | function-decl
                          | function-defition
                          | contract-impl ;