# https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_Form
digit                     = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
lower-case-letter         = "a" | ... ;
upper-case-letter         = "A" | ... ;
letter                    = upper-case-letter | lower-case-letter ;
camel-case                = upper-case-letter, { letter | digit } ;
snake-case                = lower-case-letter, { lower-case-letter | digit | "_" } ;
type-name                 = camel-case ;
contract-name             = camel-case ;
variable-name             = snake-case ;
function-name             = snake-case ;
type-var-name             = snake-case ;
api-name                  = camel-case ;
api-impl-name             = camel-case ;

type-var-name-list        = type-var-name { ",", type-var-name } ;

type                      = type-name | type-var-name;

where-limit               = type-var-name, "of", type ;
where-limit-list          = where-limit { ",", where-limit } ;
function-decl             = type, function-name, "(", function-decl-param-list, ")", [ "where", where-limit-list ], ";" ;

contract-def              = "contract", contract-name, [ "with", type-var-name-list ], "{", contract-def-content, "}" ;
contract-def-content      = function-decl, "{", function-decl, "}" ;

type-decl                 = "type", type-name, { type-var-name } ;

api-decl                  = "api", "{", { api-decl-content }, "}" ;
api-decl-content          = type-decl
                          | contract-def
                          | function-decl ;

api-impl-content          = type-def
                          | function-def
                          | contract-impl ;

api-impl                  = "api-impl", api-name, "by", api-impl-name, "{", { api-impl-content }, "}" ;

file                      = { api-decl | api-impl } ;
