# fresh-editor.spec — Fedora package for the Fresh terminal editor
#
# This packages Fresh as a *bundled Rust application*: the full crate
# dependency tree is vendored into Source1 rather than packaged as separate
# Fedora `rust-*` crate packages. This is explicitly permitted by the Fedora
# Rust Packaging Guidelines for leaf binary applications whose dependency
# trees are impractical to package individually (oxc, wgpu, tree-sitter
# grammars, etc.).
#   https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_packaging_applications
#
# Because dependencies are bundled, the effective License is the AND of the
# application's own license and every bundled crate's license. The value below
# is a STARTING POINT covering Fresh's own code; it MUST be replaced with the
# full computed expression before submission — see fedora/README.md
# ("Generate the bundled-license expression").

%global appname fresh
# GitHub archive expands to fresh-%%{version}/ (repo is named "fresh", not
# "fresh-editor"), so %%autosetup needs -n fresh-%%{version}.
%global archivedir fresh-%{version}

Name:           fresh-editor
Version:        0.4.0
Release:        %autorelease
Summary:        Lightweight, fast terminal text editor with LSP and TypeScript plugins

# SourceLicense is the license of Fresh's own source. The actual LICENSE file
# is GPLv2 *with the "or (at your option) any later version" clause*, so the
# correct SPDX identifier is GPL-2.0-or-later (NOT the deprecated bare
# "GPL-2.0" currently in Cargo.toml — fix that upstream too).
SourceLicense:  GPL-2.0-or-later
# FIXME: replace with the full bundled-dependency license expression produced
# by `fedora/gen-bundled-license.sh` (GPL-2.0-or-later AND (MIT OR Apache-2.0) AND ...).
License:        GPL-2.0-or-later AND (MIT OR Apache-2.0) AND MIT AND Apache-2.0 AND ISC AND BSD-3-Clause AND Unicode-3.0 AND MPL-2.0 AND Zlib

URL:            https://github.com/sinelaw/fresh
Source0:        %{url}/archive/v%{version}/%{archivedir}.tar.gz
# Vendored dependencies — generated by fedora/gen-vendor.sh
Source1:        %{name}-%{version}-vendor.tar.zst

# Native code is built for the terminal editor only:
#   - tree-sitter grammars (C), onig_sys / oniguruma (C), rquickjs-sys
#     (QuickJS C + bindgen), ring (crypto), portable-pty / alacritty_terminal.
ExclusiveArch:  %{rust_arches}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  gcc
# clang provides libclang, required by bindgen (rquickjs-sys).
BuildRequires:  clang
BuildRequires:  pkgconf-pkg-config
# Desktop/man/icon install + validation
BuildRequires:  desktop-file-utils
BuildRequires:  /usr/bin/desktop-file-validate

%global _description %{expand:
Fresh is a lightweight, fast terminal-based text editor with LSP support and
TypeScript plugins. It provides syntax highlighting, code completion, mouse
support, and other IDE-like features in a minimal terminal interface. Plugins
and color themes are compiled into the binary, so no additional runtime data
is installed.}

%description %{_description}

%prep
%autosetup -n %{archivedir} -p1
# Unpack the vendored crate sources (Source1). Fedora's %cargo_prep does NOT
# auto-extract a vendor tarball — its -V flag errors on Fedora — so we extract
# it ourselves; the resulting directory name must match the -v argument below.
tar --extract --file %{SOURCE1}
# Point cargo at the vendored sources (writes .cargo/config.toml, offline mode).
%cargo_prep -v vendor

%build
# Build only the `fresh` terminal binary from the fresh-editor crate with its
# default features (plugins, runtime, embed-plugins, tree-sitter, http).
# The fresh-gui crate and the dev-only bins (generate_schema, event_debug,
# measure_startup) are intentionally not built.
%cargo_build -- -p fresh-editor --bin fresh

%install
# %%cargo_build builds the `rpm` profile into target/rpm/ (it also symlinks
# target/release -> rpm). Install the binary explicitly rather than via
# %%cargo_install so the GUI/dev binaries in the workspace are not pulled in.
install -Dpm0755 target/rpm/%{appname} %{buildroot}%{_bindir}/%{appname}

# Man page
install -Dpm0644 crates/fresh-editor/resources/%{appname}.1 %{buildroot}%{_mandir}/man1/%{appname}.1

# Desktop entry (terminal editor only; fresh-gui.desktop is for the GUI build)
desktop-file-install \
    --dir=%{buildroot}%{_datadir}/applications \
    crates/fresh-editor/resources/%{appname}.desktop

# Hicolor icons
for size in 16 22 24 32 48 64 128 256 512; do
    install -Dpm0644 \
        docs/icons/linux/hicolor/${size}x${size}/apps/%{appname}.png \
        %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/%{appname}.png
done

%check
%{buildroot}%{_bindir}/%{appname} --version
desktop-file-validate %{buildroot}%{_datadir}/applications/%{appname}.desktop

%files
%license LICENSE
%doc README.md
%{_bindir}/%{appname}
%{_mandir}/man1/%{appname}.1.*
%{_datadir}/applications/%{appname}.desktop
%{_datadir}/icons/hicolor/*/apps/%{appname}.png

%changelog
%autochangelog
