//! Errors, with rquickjs's variants and messages (plugins and tests match on
//! the message text, e.g. "Error converting from js 'undefined' into type
//! 'string'").

use super::{ffi, Ctx};
use std::ffi::{CString, NulError};
use std::fmt;
use std::str::Utf8Error;

/// Result type of the engine API.
pub type Result<T> = std::result::Result<T, Error>;

/// An error from the engine or from converting between JS and Rust.
#[derive(Debug)]
pub enum Error {
    /// Could not allocate memory.
    Allocation,
    /// A string contained an interior NUL byte.
    InvalidString(NulError),
    /// A string from the engine was not UTF-8.
    Utf8(Utf8Error),
    /// A JS exception is pending; [`Ctx::catch`] retrieves it.
    Exception,
    /// Error converting from JavaScript to a Rust type.
    FromJs {
        from: &'static str,
        to: &'static str,
        message: Option<String>,
    },
    /// Error converting to JavaScript from a Rust type.
    IntoJs {
        from: &'static str,
        to: &'static str,
        message: Option<String>,
    },
    /// A function was called with fewer arguments than it requires.
    MissingArgs { expected: usize, given: usize },
    /// A function was called with more arguments than it accepts.
    TooManyArgs { expected: usize, given: usize },
    /// A persistent value was restored in a different runtime.
    UnrelatedRuntime,
    /// An error whose specifics are unknown.
    Unknown,
}

impl Error {
    pub fn is_exception(&self) -> bool {
        matches!(self, Error::Exception)
    }

    pub fn new_from_js(from: &'static str, to: &'static str) -> Self {
        Error::FromJs {
            from,
            to,
            message: None,
        }
    }

    pub fn new_from_js_message<M>(from: &'static str, to: &'static str, msg: M) -> Self
    where
        String: From<M>,
    {
        Error::FromJs {
            from,
            to,
            message: Some(msg.into()),
        }
    }

    pub fn new_into_js(from: &'static str, to: &'static str) -> Self {
        Error::IntoJs {
            from,
            to,
            message: None,
        }
    }

    pub fn new_into_js_message<M>(from: &'static str, to: &'static str, msg: M) -> Self
    where
        String: From<M>,
    {
        Error::IntoJs {
            from,
            to,
            message: Some(msg.into()),
        }
    }

    pub fn is_from_js(&self) -> bool {
        matches!(self, Error::FromJs { .. })
    }

    pub fn is_into_js(&self) -> bool {
        matches!(self, Error::IntoJs { .. })
    }

    pub fn is_num_args(&self) -> bool {
        matches!(self, Error::TooManyArgs { .. } | Error::MissingArgs { .. })
    }

    /// Raise this error in JS (as rquickjs does) and return the exception
    /// marker for a native function to return.
    pub(crate) fn throw(&self, ctx: &Ctx<'_>) -> ffi::JSValue {
        let raw = ctx.as_ptr();
        unsafe {
            match self {
                Error::Exception => ffi::fqjs_exception(),
                Error::Allocation => ffi::JS_ThrowOutOfMemory(raw),
                Error::Unknown | Error::UnrelatedRuntime => {
                    let msg = message_cstring(self);
                    ffi::JS_ThrowInternalError(raw, c"%s".as_ptr(), msg.as_ptr())
                }
                _ => {
                    let msg = message_cstring(self);
                    ffi::JS_ThrowTypeError(raw, c"%s".as_ptr(), msg.as_ptr())
                }
            }
        }
    }
}

fn message_cstring(e: &Error) -> CString {
    CString::new(e.to_string().replace('\0', "\\0")).unwrap_or_default()
}

fn with_message(f: &mut fmt::Formatter<'_>, message: &Option<String>) -> fmt::Result {
    if let Some(message) = message {
        if !message.is_empty() {
            f.write_str(": ")?;
            f.write_str(message)?;
        }
    }
    Ok(())
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::Allocation => f.write_str("Allocation failed while creating object"),
            Error::InvalidString(e) => write!(f, "String contained internal null bytes: {e}"),
            Error::Utf8(e) => write!(f, "Conversion from string failed: {e}"),
            Error::Unknown => f.write_str("QuickJS library created a unknown error"),
            Error::Exception => f.write_str("Exception generated by QuickJS"),
            Error::FromJs { from, to, message } => {
                write!(f, "Error converting from js '{from}' into type '{to}'")?;
                with_message(f, message)
            }
            Error::IntoJs { from, to, message } => {
                write!(f, "Error converting from '{from}' into js '{to}'")?;
                with_message(f, message)
            }
            Error::MissingArgs { expected, given } => write!(
                f,
                "Error calling function with {given} argument(s) while {expected} where expected"
            ),
            Error::TooManyArgs { expected, given } => write!(
                f,
                "Error calling function with {given} argument(s), function is exhaustive and cannot be called with more then {expected} arguments"
            ),
            Error::UnrelatedRuntime => {
                f.write_str("Restoring Persistent in an unrelated runtime")
            }
        }
    }
}

impl std::error::Error for Error {}

impl From<NulError> for Error {
    fn from(e: NulError) -> Self {
        Error::InvalidString(e)
    }
}

impl From<Utf8Error> for Error {
    fn from(e: Utf8Error) -> Self {
        Error::Utf8(e)
    }
}
