//! Combination meta-test — see `docs/internal/scenario-meta-testing.md`
//! ("3. Combination with active reset").
//!
//! Real `BufferScenario`s from the canonical [`super::corpus`] run on
//! ONE long-lived harness with an *active reset* (`reset::reset_actions`,
//! not a fresh harness) between them. Each scenario asserts its **own**
//! expectations at its checkpoint — right after its actions, before the
//! next reset — in fixed and randomly-permuted orders. A scenario that
//! passes alone but fails after some predecessor means either the reset
//! is incomplete or the scenario depends on ambient state a predecessor
//! left behind: bugs the fresh-harness-per-test model can't surface.
//!
//! Scope: the driver replays each scenario's `actions` (not `events`)
//! on a default no-plugins harness (auto-close/indent off, so the
//! reset's retyping is literal). So we take the corpus subset that is
//! `actions`-only, default-language, default-behavior.

use crate::common::scenario::buffer_scenario::BufferScenario;
use crate::common::scenario::property::run_scenarios_with_reset_between;
use crate::semantic::corpus;
use proptest::prelude::*;

/// Corpus scenarios the combination driver can faithfully replay.
fn combination_scenarios() -> Vec<BufferScenario> {
    corpus::buffer_scenarios()
        .into_iter()
        .filter(|s| {
            s.events.is_empty()
                && s.language.is_none()
                && !s.behavior.auto_close
                && !s.behavior.auto_indent
                && !s.behavior.auto_surround
        })
        .collect()
}

/// Representative fixed orders: forward, reverse, and a rotation.
fn orders(n: usize) -> Vec<Vec<usize>> {
    let fwd: Vec<usize> = (0..n).collect();
    let rev: Vec<usize> = (0..n).rev().collect();
    let rot: Vec<usize> = (0..n).map(|i| (i + n / 2) % n).collect();
    vec![fwd, rev, rot]
}

/// A random permutation of `0..n`, generated by sorting the indices by
/// a random key. Always a valid permutation; reproducible via
/// proptest's seed / regression file.
fn permutation_of(n: usize) -> impl Strategy<Value = Vec<usize>> {
    prop::collection::vec(any::<u64>(), n).prop_map(move |keys| {
        let mut order: Vec<usize> = (0..n).collect();
        order.sort_by_key(|&i| keys[i]);
        order
    })
}

fn assert_all_pass(scenarios: &[BufferScenario], order: &[usize]) -> Result<(), String> {
    let results = run_scenarios_with_reset_between(scenarios, order);
    for (slot, &i) in order.iter().enumerate() {
        if let Err(f) = &results[slot] {
            return Err(format!(
                "scenario {i} ({:?}) failed its own assertion under order {order:?}: {f}",
                scenarios[i].description
            ));
        }
    }
    Ok(())
}

#[test]
fn combination_corpus_passes_under_fixed_orders() {
    let scenarios = combination_scenarios();
    assert!(
        !scenarios.is_empty(),
        "no combination-eligible scenarios in corpus::buffer_scenarios()"
    );
    for order in orders(scenarios.len()) {
        if let Err(e) = assert_all_pass(&scenarios, &order) {
            panic!("{e}");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 64,
        .. ProptestConfig::default()
    })]

    /// Every corpus scenario satisfies its own assertions regardless of
    /// what ran before it (random orders, active reset between).
    #[test]
    fn combination_corpus_passes_under_random_permutation(
        order in permutation_of(combination_scenarios().len())
    ) {
        let scenarios = combination_scenarios();
        if let Err(e) = assert_all_pass(&scenarios, &order) {
            prop_assert!(false, "{}", e);
        }
    }
}
